PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS users (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  email TEXT NOT NULL UNIQUE,
  password_hash TEXT NOT NULL,
  role TEXT NOT NULL CHECK(role IN ('ADMIN','EXEC','MEMBER')),
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS projects (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  title TEXT NOT NULL,
  short_description TEXT NOT NULL DEFAULT '',
  status TEXT NOT NULL CHECK(status IN ('NOT_STARTED','IN_PROGRESS','AT_RISK','BLOCKED','DONE')) DEFAULT 'NOT_STARTED',
  priority TEXT NOT NULL CHECK(priority IN ('P0','P1','P2','P3')) DEFAULT 'P2',
  owner_user_id INTEGER NOT NULL REFERENCES users(id),
  sponsor_name TEXT NOT NULL DEFAULT '',
  start_date TEXT,
  target_date TEXT,
  tags TEXT NOT NULL DEFAULT '[]',
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS decisions (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  project_id INTEGER REFERENCES projects(id),
  title TEXT NOT NULL,
  decision_type TEXT NOT NULL CHECK(decision_type IN ('STRATEGIC','FINANCIAL','OPERATIONAL','GOVERNANCE')),
  status TEXT NOT NULL CHECK(status IN ('PROPOSED','DECIDED','REVISIT','CANCELLED')) DEFAULT 'PROPOSED',
  decision_date TEXT,
  owner_user_id INTEGER NOT NULL REFERENCES users(id),
  approver TEXT NOT NULL DEFAULT '',
  rationale TEXT NOT NULL DEFAULT '',
  options_considered TEXT NOT NULL DEFAULT '',
  decision_outcome TEXT NOT NULL DEFAULT '',
  due_date TEXT,
  impact_level TEXT NOT NULL CHECK(impact_level IN ('LOW','MED','HIGH')) DEFAULT 'MED',
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS action_items (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  project_id INTEGER REFERENCES projects(id),
  decision_id INTEGER REFERENCES decisions(id),
  title TEXT NOT NULL,
  owner_user_id INTEGER NOT NULL REFERENCES users(id),
  status TEXT NOT NULL CHECK(status IN ('OPEN','IN_PROGRESS','DONE','CANCELLED')) DEFAULT 'OPEN',
  due_date TEXT,
  notes TEXT NOT NULL DEFAULT '',
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS stakeholders (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  title TEXT NOT NULL DEFAULT '',
  org_unit TEXT NOT NULL DEFAULT '',
  contact TEXT,
  influence_level TEXT NOT NULL CHECK(influence_level IN ('LOW','MED','HIGH')) DEFAULT 'MED',
  stance TEXT NOT NULL CHECK(stance IN ('SUPPORTIVE','NEUTRAL','RESISTANT')) DEFAULT 'NEUTRAL',
  notes TEXT NOT NULL DEFAULT '',
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS project_stakeholders (
  project_id INTEGER NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  stakeholder_id INTEGER NOT NULL REFERENCES stakeholders(id) ON DELETE CASCADE,
  relationship_notes TEXT NOT NULL DEFAULT '',
  PRIMARY KEY(project_id, stakeholder_id)
);

CREATE TABLE IF NOT EXISTS risk_issues (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  project_id INTEGER NOT NULL REFERENCES projects(id),
  type TEXT NOT NULL CHECK(type IN ('RISK','ISSUE')),
  title TEXT NOT NULL,
  description TEXT NOT NULL DEFAULT '',
  probability INTEGER NOT NULL CHECK(probability BETWEEN 1 AND 5),
  impact INTEGER NOT NULL CHECK(impact BETWEEN 1 AND 5),
  status TEXT NOT NULL CHECK(status IN ('OPEN','MITIGATED','CLOSED')) DEFAULT 'OPEN',
  owner_user_id INTEGER NOT NULL REFERENCES users(id),
  mitigation_plan TEXT NOT NULL DEFAULT '',
  due_date TEXT,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS activity_logs (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  entity_type TEXT NOT NULL,
  entity_id INTEGER NOT NULL,
  action TEXT NOT NULL,
  actor_user_id INTEGER NOT NULL REFERENCES users(id),
  metadata TEXT NOT NULL DEFAULT '{}',
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS sessions (
  token TEXT PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
